---
- name: Install PHP7 and extensions
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ php_packages }}"

- include: pecl-memcache/main.yml

- name: Start PHP-FPM
  service:
    name: php-fpm
    state: started
    enabled: true
