---
- name: "Provision Vagrant"
  hosts: default
  become: yes
  become_method: sudo
  gather_facts: yes
  force_handlers: true
  any_errors_fatal: true

  roles:
    - common
    - repo_install
    - mysql
    - php71
    - nginx
    - beanstalkd
    - redis
    - memcached
    - composer
    - bash
