---
- name: "Provision Vagrant"
  hosts: default
  become: yes
  become_method: sudo
  remote_user: vagrant
  force_handlers: true
  any_errors_fatal: true

  roles:
    - common
    - repo_install
    - mysql
    - php7
    - nginx
    - beanstalkd
    - redis
    - memcached
    - composer
    - bash
