---
- name: Add html folder
  file:
    path: /var/www/html/
    state: directory
    mode: 0755
    owner: vagrant
    group: vagrant

- name: Copy fastcgi_params
  template:
    src: fastcgi_params.j2
    dest: /etc/nginx/fastcgi_params
    mode: 0644
    owner: root
    group: root

- name: Configure base nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart Nginx

- name: Configure default node
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
    owner: root
    group: root
  notify: Restart Nginx
