---
- name: Add Nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    mode: 0644
    owner: root
    group: root

- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: true
