---
- name: Install composer packages globally
  become: yes
  become_user: "{{ developer_user }}"
  shell: >
    COMPOSER_HOME={{ composer_home_path }}
    composer global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress
    creates={{ composer_home_path }}/vendor/{{ item.name }}
  register: composer_global_require_result
  with_items: "{{ composer_global_packages }}"
