---
- name: Install memcached
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libevent
    - libevent-devel
    - memcached
    - telnet

- name: Start memcached
  service:
    name: memcached
    state: started
    enabled: true
