---
- name: Start MySQL service
  service:
    name: mysqld
    state: started

- name: Create new password for root user
  command: "{{ item }}"
  with_items:
    - "mysqladmin -u root password {{ mysql_root_password }}"
    - "touch {{ mysql_data_directory }}/.mysql-root-password-has-been-set-by-ansible"
  args:
    creates: "{{ mysql_data_directory }}/.mysql-root-password-has-been-set-by-ansible"

- name: Set .my.cnf for root user
  template:
    src: .my.cnf.j2
    dest: ~/.my.cnf
    mode: 0600
    owner: root
    group: root

- name: Set .my.cnf for developer user
  template:
    src: .my.cnf.j2
    dest: "/home/{{ developer_user }}/.my.cnf"
    mode: 0600
    owner: "{{ developer_user }}"
    group: "{{ developer_user }}"

- name: Remove anonymous users
  mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
